### ISSUE TITLE
Make function() behavior consistent

### ISSUE THREAD

**Issue by wyozi** [FPtje/Sublime-GLua-Highlight#12]
Would it be possible to make it so that when you press enter after ```function(x, y)``` it would create the closing ```end``` keyword as well. That would make my life significantly easier and would make it consistent with behavior of eg. ```for```.

**Comment by FPtje** [comment]
I added a thing, but it isn't that great. You have to press tab, sometimes twice. I don't know why. The problem is that the snippets system in sublime really isn't that powerful. It suffers the same problem as the `if`, only in function definitions it *kind of* knows that the `)` belongs to a function definition and not some expression. I don't know how I can otherwise solve this.
