### ISSUE TITLE
Is it possible to make variables come as first result in autocomplete?

### ISSUE THREAD

**Issue by Luka2477** [FPtje/Sublime-GLua-Highlight#35]
The thread title says it all :) This would be very convenient :)

**Comment by FPtje** [comment]
Posting this here for later reference:
https://forum.sublimetext.com/t/change-priority-of-completions/8002

**Comment by FPtje** [comment]
Yeah, the `all autocomplete` does seem to resolve this. Check it out here:

https://packagecontrol.io/packages/All%20Autocomplete

I'll install it for myself too, since it's been bugging me too. 

As for this repository, I'd argue that it's not an issue specific to GLua. It's an issue of the editor. It applies to all languages. With that in mind I think an update for sublime or indeed a package such as `all autocomplete` are in the right position to deal with it.
